// frontend-svelte/src/routes/projects/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { goto } from '$app/navigation';
  import { X } from 'lucide-svelte';
  import * as tauri from '$lib/tauri';
  import { appStore } from '$lib/stores/app.svelte';
  import ThreadListSkeleton from '$lib/components/ui/ThreadListSkeleton.svelte';

  type Project = {
    id: number;
    name: string;
    description?: string;
    instructions?: string;
    context_data?: string;
  };

  type Thread = {
    id: string;
    title?: string | null;
  };

  type Status = { type: 'success' | 'error'; text: string } | null;

  let projects = $state<Project[]>([]);
  let selectedProject = $state<Project | null>(null);
  let threads = $state<Thread[]>([]);
  let loadingProjects = $state(false);
  let loadingThreads = $state(false);
  let status = $state<Status>(null);
  let confirmProjectDelete = $state(false);
  let confirmThreadDelete = $state<{ open: boolean; threadId: string | null }>({ open: false, threadId: null });
  let editingThreadId = $state<string | null>(null);
  let editingThreadTitle = $state('');

  let newProject = $state({ name: '', description: '', instructions: '', context_data: '' });
  let editProject = $state({ name: '', description: '', instructions: '', context_data: '' });

  async function loadProjects() {
    loadingProjects = true;
    try {
      const data = await tauri.listProjects();
      projects = (data || []) as Project[];
    } catch (err) {
      console.error(err);
    } finally {
      loadingProjects = false;
    }
  }

  async function loadThreads(projectId: number) {
    loadingThreads = true;
    try {
      const data = await tauri.listThreads(projectId);
      threads = (data || []) as Thread[];
    } catch (err) {
      console.error(err);
    } finally {
      loadingThreads = false;
    }
  }

  function selectProject(project: Project) {
    selectedProject = project;
    editProject = {
      name: project.name || '',
      description: project.description || '',
      instructions: project.instructions || '',
      context_data: project.context_data || '',
    };
    loadThreads(project.id);
  }

  async function handleCreate() {
    if (!newProject.name.trim()) return;
    try {
      const created = await tauri.createProject(newProject) as Project;
      newProject = { name: '', description: '', instructions: '', context_data: '' };
      status = { type: 'success', text: 'Projet cree.' };
      await loadProjects();
      if (created?.id) selectProject(created);
    } catch (err) {
      console.error(err);
      status = { type: 'error', text: 'Impossible de creer le projet.' };
    }
  }

  async function handleUpdate() {
    if (!selectedProject) return;
    try {
      await tauri.updateProject(selectedProject.id, editProject);
      status = { type: 'success', text: 'Projet mis a jour.' };
      await loadProjects();
    } catch (err) {
      console.error(err);
      status = { type: 'error', text: 'Impossible de mettre a jour le projet.' };
    }
  }

  async function handleDelete() {
    if (!selectedProject) return;
    try {
      await tauri.deleteProject(selectedProject.id);
      selectedProject = null;
      threads = [];
      status = { type: 'success', text: 'Projet supprime.' };
      await loadProjects();
    } catch (err) {
      console.error(err);
      status = { type: 'error', text: 'Impossible de supprimer le projet.' };
    }
  }

  async function handleDeleteThread(threadId: string) {
    if (!selectedProject) return;
    try {
      await tauri.deleteThread(threadId);
      await loadThreads(selectedProject.id);
    } catch (err) {
      console.error(err);
      status = { type: 'error', text: 'Impossible de supprimer la conversation.' };
    }
  }

  async function handleRenameThread(threadId: string) {
    if (!selectedProject) return;
    try {
      await tauri.updateThread(threadId, { title: editingThreadTitle });
      status = { type: 'success', text: 'Conversation renommee.' };
      editingThreadId = null;
      editingThreadTitle = '';
      await loadThreads(selectedProject.id);
    } catch (err) {
      console.error(err);
      status = { type: 'error', text: 'Impossible de renommer la conversation.' };
    }
  }

  function openInChat(projectId: number, threadId?: string) {
    appStore.setSelectedProjectId(projectId);
    if (threadId) appStore.setSelectedThreadId(threadId);
    goto('/');
  }

  onMount(() => {
    loadProjects();
  });
</script>

<div class="relative min-h-full overflow-x-hidden text-gray-900 dark:text-foreground">
  <div class="mx-auto max-w-6xl px-4 py-10">
    <!-- Header -->
    <div class="mb-8 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
      <div>
        <p class="text-xs uppercase tracking-[0.2em] text-gray-400 dark:text-muted-foreground">Projets</p>
        <h1 class="text-3xl font-semibold text-gray-900 dark:text-foreground">Espace projets</h1>
        <p class="text-sm text-gray-500 dark:text-muted-foreground">Gerer les instructions et le contexte de chaque projet.</p>
      </div>
      <div class="flex flex-wrap items-center gap-2">
        <a
          href="/"
          class="inline-flex items-center gap-1.5 rounded-full border border-gray-200 bg-white px-4 py-2 text-xs font-medium text-gray-600 transition hover:bg-gray-100 hover:text-gray-800 dark:border-border dark:bg-muted dark:text-muted-foreground dark:hover:bg-muted dark:hover:text-foreground"
        >
          <X class="h-3.5 w-3.5" />
          Fermer
        </a>
      </div>
    </div>

    <!-- Status banner -->
    {#if status}
      <div
        class={`mb-6 rounded-xl border px-4 py-3 text-sm ${
          status.type === 'success'
            ? 'border-emerald-200 bg-emerald-50 text-emerald-700 dark:border-emerald-500/30 dark:bg-emerald-500/10 dark:text-emerald-200'
            : 'border-red-200 bg-red-50 text-red-700 dark:border-red-500/30 dark:bg-red-500/10 dark:text-red-200'
        }`}
      >
        {status.text}
      </div>
    {/if}

    <div class="grid gap-6 lg:grid-cols-[1.1fr_1.4fr]">
      <!-- Create project -->
      <section class="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm dark:border-border dark:bg-card/60 dark:shadow-none">
        <h2 class="text-lg font-semibold text-gray-900 dark:text-foreground">Creer un projet</h2>
        <div class="mt-4 grid gap-4">
          <input
            bind:value={newProject.name}
            type="text"
            placeholder="Nom du projet"
            class="w-full rounded-xl border border-gray-200 bg-gray-50 px-3 py-2 text-sm text-gray-700 outline-none focus:border-teal-400 focus:ring-2 focus:ring-teal-200 dark:border-border dark:bg-card dark:text-foreground dark:focus:ring-teal-400/30"
          />
          <input
            bind:value={newProject.description}
            type="text"
            placeholder="Description courte (optionnel)"
            class="w-full rounded-xl border border-gray-200 bg-gray-50 px-3 py-2 text-sm text-gray-700 outline-none focus:border-teal-400 focus:ring-2 focus:ring-teal-200 dark:border-border dark:bg-card dark:text-foreground dark:focus:ring-teal-400/30"
          />
          <textarea
            bind:value={newProject.instructions}
            rows={4}
            placeholder="Instructions pour l'IA (optionnel)"
            class="w-full resize-none rounded-xl border border-gray-200 bg-gray-50 px-3 py-2 text-sm text-gray-700 outline-none focus:border-teal-400 focus:ring-2 focus:ring-teal-200 dark:border-border dark:bg-card dark:text-foreground dark:focus:ring-teal-400/30"
          ></textarea>
          <textarea
            bind:value={newProject.context_data}
            rows={4}
            placeholder="Donnees de contexte (optionnel)"
            class="w-full resize-none rounded-xl border border-gray-200 bg-gray-50 px-3 py-2 text-sm text-gray-700 outline-none focus:border-teal-400 focus:ring-2 focus:ring-teal-200 dark:border-border dark:bg-card dark:text-foreground dark:focus:ring-teal-400/30"
          ></textarea>
          <button
            type="button"
            onclick={handleCreate}
            class="inline-flex items-center justify-center rounded-full bg-teal-500 px-5 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-teal-600"
          >
            Creer le projet
          </button>
        </div>
      </section>

      <!-- Project list + detail -->
      <section class="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm dark:border-border dark:bg-card/60 dark:shadow-none">
        <h2 class="text-lg font-semibold text-gray-900 dark:text-foreground">Vos projets</h2>
        <div class="mt-4 grid gap-3">
          {#if loadingProjects}
            <div class="space-y-2">
              {#each Array(3) as _}
                <div class="h-14 animate-pulse rounded-xl bg-gray-100 dark:bg-muted"></div>
              {/each}
            </div>
          {:else if projects.length === 0}
            <p class="text-sm text-gray-500 dark:text-muted-foreground">Aucun projet pour le moment.</p>
          {:else}
            {#each projects as project (project.id)}
              <div
                class={`rounded-xl border px-4 py-3 text-sm transition ${
                  selectedProject?.id === project.id
                    ? 'border-teal-200 bg-teal-50 text-teal-700 dark:border-teal-500/40 dark:bg-teal-500/10 dark:text-teal-100'
                    : 'border-gray-200 bg-gray-50 text-gray-700 hover:border-teal-200 hover:bg-teal-50 dark:border-border dark:bg-card/60 dark:text-foreground dark:hover:border-teal-500/40 dark:hover:bg-teal-500/10'
                }`}
              >
                <button
                  type="button"
                  onclick={() => selectProject(project)}
                  class="w-full text-left"
                >
                  <p class="font-semibold">{project.name}</p>
                  <p class="text-xs text-gray-500 dark:text-muted-foreground">
                    {project.description || 'Aucune description'}
                  </p>
                </button>
                <button
                  type="button"
                  onclick={() => openInChat(project.id)}
                  class="mt-2 inline-flex text-xs font-semibold text-teal-600 hover:text-teal-700 dark:text-teal-300 dark:hover:text-teal-200"
                >
                  Ouvrir dans le chat
                </button>
              </div>
            {/each}
          {/if}
        </div>

        {#if selectedProject}
          <div class="mt-6 rounded-2xl border border-gray-100 bg-gray-50 p-4 dark:border-border dark:bg-card/60">
            <h3 class="text-sm font-semibold text-gray-700 dark:text-foreground">Modifier le projet</h3>
            <button
              type="button"
              onclick={() => openInChat(selectedProject!.id)}
              class="mt-2 inline-flex text-xs font-semibold text-teal-600 hover:text-teal-700 dark:text-teal-300 dark:hover:text-teal-200"
            >
              Ouvrir le projet dans le chat
            </button>
            <div class="mt-3 grid gap-3">
              <input
                bind:value={editProject.name}
                type="text"
                class="w-full rounded-xl border border-gray-200 bg-white px-3 py-2 text-sm text-gray-700 outline-none focus:border-teal-400 focus:ring-2 focus:ring-teal-200 dark:border-border dark:bg-card dark:text-foreground dark:focus:ring-teal-400/30"
              />
              <input
                bind:value={editProject.description}
                type="text"
                class="w-full rounded-xl border border-gray-200 bg-white px-3 py-2 text-sm text-gray-700 outline-none focus:border-teal-400 focus:ring-2 focus:ring-teal-200 dark:border-border dark:bg-card dark:text-foreground dark:focus:ring-teal-400/30"
              />
              <textarea
                bind:value={editProject.instructions}
                rows={4}
                class="w-full resize-none rounded-xl border border-gray-200 bg-white px-3 py-2 text-sm text-gray-700 outline-none focus:border-teal-400 focus:ring-2 focus:ring-teal-200 dark:border-border dark:bg-card dark:text-foreground dark:focus:ring-teal-400/30"
              ></textarea>
              <textarea
                bind:value={editProject.context_data}
                rows={4}
                class="w-full resize-none rounded-xl border border-gray-200 bg-white px-3 py-2 text-sm text-gray-700 outline-none focus:border-teal-400 focus:ring-2 focus:ring-teal-200 dark:border-border dark:bg-card dark:text-foreground dark:focus:ring-teal-400/30"
              ></textarea>
              <div class="flex flex-wrap gap-2">
                <button
                  type="button"
                  onclick={handleUpdate}
                  class="rounded-full bg-teal-500 px-4 py-2 text-xs font-semibold text-white shadow-sm transition hover:bg-teal-600"
                >
                  Enregistrer
                </button>
                <button
                  type="button"
                  onclick={() => { confirmProjectDelete = true; }}
                  class="rounded-full border border-red-300 px-4 py-2 text-xs font-semibold text-red-600 transition hover:bg-red-50 dark:border-red-500/40 dark:text-red-200 dark:hover:bg-red-500/10"
                >
                  Supprimer le projet
                </button>
              </div>
            </div>

            <!-- Conversations -->
            <div class="mt-6 border-t border-gray-200 pt-4 dark:border-border">
              <h4 class="text-sm font-semibold text-gray-700 dark:text-foreground">Conversations</h4>
              <div class="mt-3 space-y-2">
                {#if loadingThreads}
                  <ThreadListSkeleton />
                {:else if threads.length === 0}
                  <p class="text-xs text-gray-500 dark:text-muted-foreground">Aucune conversation pour ce projet.</p>
                {:else}
                  {#each threads as thread (thread.id)}
                    <div class="flex items-center justify-between rounded-lg border border-gray-200 bg-white px-3 py-2 text-xs dark:border-border dark:bg-card">
                      {#if editingThreadId === thread.id}
                        <input
                          bind:value={editingThreadTitle}
                          type="text"
                          placeholder="Titre de conversation"
                          class="mr-3 flex-1 rounded-lg border border-gray-200 bg-gray-50 px-2 py-1 text-xs text-gray-700 outline-none focus:border-teal-400 focus:ring-2 focus:ring-teal-200 dark:border-border dark:bg-card dark:text-foreground dark:focus:ring-teal-400/30"
                        />
                      {:else}
                        <span class="font-semibold text-gray-700 dark:text-foreground">
                          {thread.title || 'Conversation sans titre'}
                        </span>
                      {/if}
                      <div class="flex items-center gap-2">
                        {#if editingThreadId === thread.id}
                          <button
                            type="button"
                            onclick={() => handleRenameThread(thread.id)}
                            class="text-xs font-semibold text-teal-600 hover:text-teal-700 dark:text-teal-300 dark:hover:text-teal-200"
                          >
                            Enregistrer
                          </button>
                          <button
                            type="button"
                            onclick={() => { editingThreadId = null; editingThreadTitle = ''; }}
                            class="text-xs font-semibold text-gray-500 hover:text-gray-700 dark:text-muted-foreground dark:hover:text-foreground"
                          >
                            Annuler
                          </button>
                        {:else}
                          <button
                            type="button"
                            onclick={() => openInChat(selectedProject!.id, thread.id)}
                            class="text-xs font-semibold text-teal-600 hover:text-teal-700 dark:text-teal-300 dark:hover:text-teal-200"
                          >
                            Ouvrir
                          </button>
                          <button
                            type="button"
                            onclick={() => { editingThreadId = thread.id; editingThreadTitle = thread.title || ''; }}
                            class="text-xs font-semibold text-gray-600 hover:text-gray-800 dark:text-muted-foreground dark:hover:text-foreground"
                          >
                            Renommer
                          </button>
                          <button
                            type="button"
                            onclick={() => { confirmThreadDelete = { open: true, threadId: thread.id }; }}
                            class="text-xs font-semibold text-red-600 hover:text-red-700 dark:text-red-300 dark:hover:text-red-200"
                          >
                            Supprimer
                          </button>
                        {/if}
                      </div>
                    </div>
                  {/each}
                {/if}
              </div>
            </div>
          </div>
        {/if}
      </section>
    </div>
  </div>

  <!-- Modal: confirm thread delete -->
  {#if confirmThreadDelete.open}
    <div class="fixed inset-0 z-50 flex items-center justify-center bg-black/40 px-4">
      <div class="w-full max-w-sm rounded-2xl bg-white p-5 shadow-xl dark:bg-card dark:shadow-none">
        <h4 class="text-base font-semibold text-gray-900 dark:text-foreground">Supprimer la conversation</h4>
        <p class="mt-2 text-sm text-gray-600 dark:text-muted-foreground">Cette action est irreversible.</p>
        <div class="mt-5 flex justify-end gap-2">
          <button
            type="button"
            class="rounded-full border border-gray-200 px-4 py-2 text-xs font-semibold text-gray-600 hover:bg-gray-50 dark:border-border dark:text-muted-foreground dark:hover:bg-muted"
            onclick={() => { confirmThreadDelete = { open: false, threadId: null }; }}
          >
            Annuler
          </button>
          <button
            type="button"
            class="rounded-full bg-red-600 px-4 py-2 text-xs font-semibold text-white hover:bg-red-700"
            onclick={() => {
              const target = confirmThreadDelete.threadId;
              confirmThreadDelete = { open: false, threadId: null };
              if (target) handleDeleteThread(target);
            }}
          >
            Supprimer
          </button>
        </div>
      </div>
    </div>
  {/if}

  <!-- Modal: confirm project delete -->
  {#if confirmProjectDelete}
    <div class="fixed inset-0 z-50 flex items-center justify-center bg-black/40 px-4">
      <div class="w-full max-w-sm rounded-2xl bg-white p-5 shadow-xl dark:bg-card dark:shadow-none">
        <h4 class="text-base font-semibold text-gray-900 dark:text-foreground">Supprimer le projet</h4>
        <p class="mt-2 text-sm text-gray-600 dark:text-muted-foreground">
          Ce projet sera supprime et ses conversations detachees. Action irreversible.
        </p>
        <div class="mt-5 flex justify-end gap-2">
          <button
            type="button"
            class="rounded-full border border-gray-200 px-4 py-2 text-xs font-semibold text-gray-600 hover:bg-gray-50 dark:border-border dark:text-muted-foreground dark:hover:bg-muted"
            onclick={() => { confirmProjectDelete = false; }}
          >
            Annuler
          </button>
          <button
            type="button"
            class="rounded-full bg-red-600 px-4 py-2 text-xs font-semibold text-white hover:bg-red-700"
            onclick={() => { confirmProjectDelete = false; handleDelete(); }}
          >
            Supprimer
          </button>
        </div>
      </div>
    </div>
  {/if}
</div>

// frontend/src/features/projects/Projects.jsx
import React, { useEffect, useState } from 'react';
import axios from 'axios';
import { API_BASE } from '../../apiConfig';
import { Link } from 'react-router-dom';

function Projects() {
  const [projects, setProjects] = useState([]);
  const [selectedProject, setSelectedProject] = useState(null);
  const [threads, setThreads] = useState([]);
  const [loadingThreads, setLoadingThreads] = useState(false);
  const [confirmThreadDelete, setConfirmThreadDelete] = useState({
    open: false,
    threadId: null,
  });
  const [editingThreadId, setEditingThreadId] = useState(null);
  const [editingThreadTitle, setEditingThreadTitle] = useState('');
  const [confirmProjectDelete, setConfirmProjectDelete] = useState(false);
  const [newProject, setNewProject] = useState({
    name: '',
    description: '',
    instructions: '',
    context_data: '',
  });
  const [editProject, setEditProject] = useState({
    name: '',
    description: '',
    instructions: '',
    context_data: '',
  });
  const [status, setStatus] = useState(null);

  const token = localStorage.getItem('token');

  const loadProjects = async () => {
    if (!token) return;
    try {
      const response = await axios.get(`${API_BASE}/api/projects`, {
        headers: { Authorization: `Bearer ${token}` },
      });
      setProjects(response.data || []);
    } catch (err) {
      console.error(err);
    }
  };

  useEffect(() => {
    loadProjects();
  }, []);

  useEffect(() => {
    if (!selectedProject) return;
    setEditProject({
      name: selectedProject.name || '',
      description: selectedProject.description || '',
      instructions: selectedProject.instructions || '',
      context_data: selectedProject.context_data || '',
    });
  }, [selectedProject]);

  const loadThreads = async projectId => {
    if (!token || !projectId) return;
    setLoadingThreads(true);
    try {
      const response = await axios.get(
        `${API_BASE}/api/projects/${projectId}/threads`,
        { headers: { Authorization: `Bearer ${token}` } },
      );
      setThreads(response.data || []);
    } catch (err) {
      console.error(err);
    } finally {
      setLoadingThreads(false);
    }
  };

  useEffect(() => {
    if (!selectedProject) {
      setThreads([]);
      setEditingThreadId(null);
      setEditingThreadTitle('');
      return;
    }
    loadThreads(selectedProject.id);
  }, [selectedProject]);

  const handleCreate = async () => {
    if (!token || !newProject.name.trim()) return;
    try {
      const response = await axios.post(
        `${API_BASE}/api/projects`,
        newProject,
        { headers: { Authorization: `Bearer ${token}` } },
      );
      setNewProject({
        name: '',
        description: '',
        instructions: '',
        context_data: '',
      });
      setStatus({ type: 'success', text: 'Projet créé.' });
      await loadProjects();
      if (response.data?.id) {
        const created = {
          ...response.data,
          id: response.data.id,
        };
        setSelectedProject(created);
      }
    } catch (err) {
      console.error(err);
      setStatus({ type: 'error', text: 'Impossible de créer le projet.' });
    }
  };

  const handleUpdate = async () => {
    if (!token || !selectedProject) return;
    try {
      await axios.patch(
        `${API_BASE}/api/projects/${selectedProject.id}`,
        editProject,
        { headers: { Authorization: `Bearer ${token}` } },
      );
      setStatus({ type: 'success', text: 'Projet mis à jour.' });
      await loadProjects();
      const refreshed = projects.find(item => item.id === selectedProject.id);
      if (refreshed) {
        setSelectedProject(refreshed);
      }
    } catch (err) {
      console.error(err);
      setStatus({
        type: 'error',
        text: 'Impossible de mettre à jour le projet.',
      });
    }
  };

  const handleDelete = async () => {
    if (!token || !selectedProject) return;
    try {
      await axios.delete(`${API_BASE}/api/projects/${selectedProject.id}`, {
        headers: { Authorization: `Bearer ${token}` },
      });
      setSelectedProject(null);
      setStatus({ type: 'success', text: 'Projet supprimé.' });
      await loadProjects();
    } catch (err) {
      console.error(err);
      setStatus({ type: 'error', text: 'Impossible de supprimer le projet.' });
    }
  };

  const handleDeleteThread = async threadId => {
    if (!token || !selectedProject) return;
    try {
      await axios.delete(`${API_BASE}/api/threads/${threadId}`, {
        headers: { Authorization: `Bearer ${token}` },
      });
      await loadThreads(selectedProject.id);
    } catch (err) {
      console.error(err);
      setStatus({
        type: 'error',
        text: 'Impossible de supprimer la conversation.',
      });
    }
  };

  const handleStartRenameThread = thread => {
    setEditingThreadId(thread.id);
    setEditingThreadTitle(thread.title || '');
  };

  const handleCancelRenameThread = () => {
    setEditingThreadId(null);
    setEditingThreadTitle('');
  };

  const handleRenameThread = async threadId => {
    if (!token || !selectedProject) return;
    try {
      await axios.patch(
        `${API_BASE}/api/threads/${threadId}`,
        { title: editingThreadTitle },
        { headers: { Authorization: `Bearer ${token}` } },
      );
      setStatus({ type: 'success', text: 'Conversation renommée.' });
      handleCancelRenameThread();
      await loadThreads(selectedProject.id);
    } catch (err) {
      console.error(err);
      setStatus({
        type: 'error',
        text: 'Impossible de renommer la conversation.',
      });
    }
  };

  return (
    <div className='min-h-screen bg-linear-to-br from-gray-50 via-white to-gray-100 text-gray-900 dark:from-slate-950 dark:via-slate-950 dark:to-slate-900 dark:text-slate-100'>
      <div className='mx-auto max-w-6xl px-4 py-10'>
        <div className='mb-8 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between'>
          <div>
            <p className='text-xs uppercase tracking-[0.2em] text-gray-400 dark:text-slate-400'>
              Projets
            </p>
            <h1 className='text-3xl font-semibold text-gray-900 dark:text-slate-100'>
              Espace projets
            </h1>
            <p className='text-sm text-gray-500 dark:text-slate-300'>
              Gérer les instructions et le contexte de chaque projet.
            </p>
          </div>
        </div>

        {status && (
          <div
            className={`mb-6 rounded-xl border px-4 py-3 text-sm ${
              status.type === 'success'
                ? 'border-emerald-200 bg-emerald-50 text-emerald-700 dark:border-emerald-500/30 dark:bg-emerald-500/10 dark:text-emerald-200'
                : 'border-red-200 bg-red-50 text-red-700 dark:border-red-500/30 dark:bg-red-500/10 dark:text-red-200'
            }`}
          >
            {status.text}
          </div>
        )}

        <div className='grid gap-6 lg:grid-cols-[1.1fr_1.4fr]'>
          <section className='rounded-2xl border border-gray-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900/60 dark:shadow-none'>
            <div className='flex items-center justify-between'>
              <h2 className='text-lg font-semibold text-gray-900 dark:text-slate-100'>
              Créer un projet
              </h2>
            </div>
            <div className='mt-4 grid gap-4'>
              <input
                type='text'
                value={newProject.name}
                onChange={event =>
                  setNewProject(prev => ({
                    ...prev,
                    name: event.target.value,
                  }))
                }
                placeholder='Nom du projet'
                className='w-full rounded-xl border border-gray-200 bg-gray-50 px-3 py-2 text-sm text-gray-700 outline-none focus:border-teal-400 focus:ring-2 focus:ring-teal-200 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-100 dark:focus:ring-teal-400/30'
              />
              <input
                type='text'
                value={newProject.description}
                onChange={event =>
                  setNewProject(prev => ({
                    ...prev,
                    description: event.target.value,
                  }))
                }
                placeholder='Description courte (optionnel)'
                className='w-full rounded-xl border border-gray-200 bg-gray-50 px-3 py-2 text-sm text-gray-700 outline-none focus:border-teal-400 focus:ring-2 focus:ring-teal-200 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-100 dark:focus:ring-teal-400/30'
              />
              <textarea
                rows={4}
                value={newProject.instructions}
                onChange={event =>
                  setNewProject(prev => ({
                    ...prev,
                    instructions: event.target.value,
                  }))
                }
                placeholder="Instructions pour l\'IA (optionnel)"
                className='w-full resize-none rounded-xl border border-gray-200 bg-gray-50 px-3 py-2 text-sm text-gray-700 outline-none focus:border-teal-400 focus:ring-2 focus:ring-teal-200 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-100 dark:focus:ring-teal-400/30'
              />
              <textarea
                rows={4}
                value={newProject.context_data}
                onChange={event =>
                  setNewProject(prev => ({
                    ...prev,
                    context_data: event.target.value,
                  }))
                }
                placeholder='Données de contexte (optionnel)'
                className='w-full resize-none rounded-xl border border-gray-200 bg-gray-50 px-3 py-2 text-sm text-gray-700 outline-none focus:border-teal-400 focus:ring-2 focus:ring-teal-200 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-100 dark:focus:ring-teal-400/30'
              />
              <button
                type='button'
                onClick={handleCreate}
                className='inline-flex items-center justify-center rounded-full bg-teal-500 px-5 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-teal-600'
              >
                Créer le projet
              </button>
            </div>
          </section>

          <section className='rounded-2xl border border-gray-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900/60 dark:shadow-none'>
            <div className='flex items-center justify-between'>
              <h2 className='text-lg font-semibold text-gray-900 dark:text-slate-100'>
                Vos projets
              </h2>
            </div>
            <div className='mt-4 grid gap-3'>
              {projects.length === 0 && (
                <p className='text-sm text-gray-500 dark:text-slate-400'>
                  Aucun projet pour le moment.
                </p>
              )}
              {projects.map(project => (
                <div
                  key={project.id}
                    className={`rounded-xl border px-4 py-3 text-left text-sm transition ${
                      selectedProject?.id === project.id
                        ? 'border-teal-200 bg-teal-50 text-teal-700 dark:border-teal-500/40 dark:bg-teal-500/10 dark:text-teal-100'
                        : 'border-gray-200 bg-gray-50 text-gray-700 hover:border-teal-200 hover:bg-teal-50 dark:border-slate-700 dark:bg-slate-900/60 dark:text-slate-200 dark:hover:border-teal-500/40 dark:hover:bg-teal-500/10'
                    }`}
                >
                  <button
                    type='button'
                    onClick={() => setSelectedProject(project)}
                    className='w-full text-left'
                  >
                    <p className='font-semibold'>{project.name}</p>
                    <p className='text-xs text-gray-500 dark:text-slate-400'>
                      {project.description || 'Aucune description'}
                    </p>
                  </button>
                  <Link
                    to={`/chat?projectId=${project.id}`}
                    className='mt-2 inline-flex text-xs font-semibold text-teal-600 hover:text-teal-700 dark:text-teal-300 dark:hover:text-teal-200'
                  >
                    Ouvrir dans le chat
                  </Link>
                </div>
              ))}
            </div>
            {selectedProject && (
              <div className='mt-6 rounded-2xl border border-gray-100 bg-gray-50 p-4 dark:border-slate-800 dark:bg-slate-900/60'>
                <h3 className='text-sm font-semibold text-gray-700 dark:text-slate-200'>
                  Modifier le projet
                </h3>
                <Link
                  to={`/chat?projectId=${selectedProject.id}`}
                  className='mt-2 inline-flex text-xs font-semibold text-teal-600 hover:text-teal-700 dark:text-teal-300 dark:hover:text-teal-200'
                >
                  Ouvrir le projet dans le chat
                </Link>
                <div className='mt-3 grid gap-3'>
                  <input
                    type='text'
                    value={editProject.name}
                    onChange={event =>
                      setEditProject(prev => ({
                        ...prev,
                        name: event.target.value,
                      }))
                    }
                    className='w-full rounded-xl border border-gray-200 bg-white px-3 py-2 text-sm text-gray-700 outline-none focus:border-teal-400 focus:ring-2 focus:ring-teal-200 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-100 dark:focus:ring-teal-400/30'
                  />
                  <input
                    type='text'
                    value={editProject.description}
                    onChange={event =>
                      setEditProject(prev => ({
                        ...prev,
                        description: event.target.value,
                      }))
                    }
                    className='w-full rounded-xl border border-gray-200 bg-white px-3 py-2 text-sm text-gray-700 outline-none focus:border-teal-400 focus:ring-2 focus:ring-teal-200 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-100 dark:focus:ring-teal-400/30'
                  />
                  <textarea
                    rows={4}
                    value={editProject.instructions}
                    onChange={event =>
                      setEditProject(prev => ({
                        ...prev,
                        instructions: event.target.value,
                      }))
                    }
                    className='w-full resize-none rounded-xl border border-gray-200 bg-white px-3 py-2 text-sm text-gray-700 outline-none focus:border-teal-400 focus:ring-2 focus:ring-teal-200 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-100 dark:focus:ring-teal-400/30'
                  />
                  <textarea
                    rows={4}
                    value={editProject.context_data}
                    onChange={event =>
                      setEditProject(prev => ({
                        ...prev,
                        context_data: event.target.value,
                      }))
                    }
                    className='w-full resize-none rounded-xl border border-gray-200 bg-white px-3 py-2 text-sm text-gray-700 outline-none focus:border-teal-400 focus:ring-2 focus:ring-teal-200 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-100 dark:focus:ring-teal-400/30'
                  />
                  <div className='flex flex-wrap gap-2'>
                    <button
                      type='button'
                      onClick={handleUpdate}
                      className='rounded-full bg-teal-500 px-4 py-2 text-xs font-semibold text-white shadow-sm transition hover:bg-teal-600'
                    >
                      Enregistrer
                    </button>
                    <button
                      type='button'
                      onClick={() => setConfirmProjectDelete(true)}
                      className='rounded-full border border-red-300 px-4 py-2 text-xs font-semibold text-red-600 transition hover:bg-red-50 dark:border-red-500/40 dark:text-red-200 dark:hover:bg-red-500/10'
                    >
                      Supprimer le projet
                    </button>
                  </div>
                </div>
                <div className='mt-6 border-t border-gray-200 pt-4 dark:border-slate-800'>
                  <div className='flex items-center justify-between'>
                    <h4 className='text-sm font-semibold text-gray-700 dark:text-slate-200'>
                      Conversations
                    </h4>
                  </div>
                  <div className='mt-3 space-y-2'>
                    {loadingThreads ? (
                      <p className='text-xs text-gray-500 dark:text-slate-400'>Chargement...</p>
                    ) : threads.length === 0 ? (
                      <p className='text-xs text-gray-500 dark:text-slate-400'>
                        Aucune conversation pour ce projet.
                      </p>
                    ) : (
                      threads.map(thread => {
                        const isEditing = editingThreadId === thread.id;
                        return (
                          <div
                            key={thread.id}
                            className='flex items-center justify-between rounded-lg border border-gray-200 bg-white px-3 py-2 text-xs dark:border-slate-700 dark:bg-slate-900'
                          >
                            {isEditing ? (
                              <input
                                type='text'
                                value={editingThreadTitle}
                                onChange={event =>
                                  setEditingThreadTitle(event.target.value)
                                }
                                placeholder='Titre de conversation'
                                className='mr-3 flex-1 rounded-lg border border-gray-200 bg-gray-50 px-2 py-1 text-xs text-gray-700 outline-none focus:border-teal-400 focus:ring-2 focus:ring-teal-200 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-100 dark:focus:ring-teal-400/30'
                              />
                            ) : (
                              <span className='font-semibold text-gray-700 dark:text-slate-200'>
                                {thread.title || 'Conversation sans titre'}
                              </span>
                            )}
                            <div className='flex items-center gap-2'>
                              {isEditing ? (
                                <>
                                  <button
                                    type='button'
                                    onClick={() => handleRenameThread(thread.id)}
                                    className='text-xs font-semibold text-teal-600 hover:text-teal-700 dark:text-teal-300 dark:hover:text-teal-200'
                                  >
                                    Enregistrer
                                  </button>
                                  <button
                                    type='button'
                                    onClick={handleCancelRenameThread}
                                    className='text-xs font-semibold text-gray-500 hover:text-gray-700 dark:text-slate-400 dark:hover:text-slate-200'
                                  >
                                    Annuler
                                  </button>
                                </>
                              ) : (
                                <>
                                  <Link
                                    to={`/chat?projectId=${selectedProject.id}&threadId=${thread.id}`}
                                    className='text-xs font-semibold text-teal-600 hover:text-teal-700 dark:text-teal-300 dark:hover:text-teal-200'
                                  >
                                    Ouvrir
                                  </Link>
                                  <button
                                    type='button'
                                    onClick={() => handleStartRenameThread(thread)}
                                    className='text-xs font-semibold text-gray-600 hover:text-gray-800 dark:text-slate-300 dark:hover:text-slate-100'
                                  >
                                    Renommer
                                  </button>
                                  <button
                                    type='button'
                                    onClick={() =>
                                      setConfirmThreadDelete({
                                        open: true,
                                        threadId: thread.id,
                                      })
                                    }
                                    className='text-xs font-semibold text-red-600 hover:text-red-700 dark:text-red-300 dark:hover:text-red-200'
                                  >
                                    Supprimer
                                  </button>
                                </>
                              )}
                            </div>
                          </div>
                        );
                      })
                    )}
                  </div>
                </div>
              </div>
            )}
          </section>
        </div>
        <div className='mt-10 flex justify-center'>
          <Link
            to='/chat'
            className='inline-flex items-center justify-center rounded-full border border-gray-200 px-5 py-2 text-xs font-semibold text-gray-600 shadow-sm transition hover:border-teal-200 hover:text-teal-600 dark:border-slate-700 dark:text-slate-300 dark:hover:border-teal-500/40 dark:hover:text-teal-200'
          >
            Retour au chat
          </Link>
        </div>
      </div>

      {confirmThreadDelete.open && (
        <div className='fixed inset-0 z-50 flex items-center justify-center bg-black/40 px-4'>
          <div className='w-full max-w-sm rounded-2xl bg-white p-5 shadow-xl dark:bg-slate-900 dark:shadow-none'>
            <h4 className='text-base font-semibold text-gray-900 dark:text-slate-100'>
              Supprimer la conversation
            </h4>
            <p className='mt-2 text-sm text-gray-600 dark:text-slate-300'>
              Cette action est irréversible.
            </p>
            <div className='mt-5 flex justify-end gap-2'>
              <button
                type='button'
                className='rounded-full border border-gray-200 px-4 py-2 text-xs font-semibold text-gray-600 hover:bg-gray-50 dark:border-slate-700 dark:text-slate-300 dark:hover:bg-slate-800'
                onClick={() =>
                  setConfirmThreadDelete({ open: false, threadId: null })
                }
              >
                Annuler
              </button>
              <button
                type='button'
                className='rounded-full bg-red-600 px-4 py-2 text-xs font-semibold text-white hover:bg-red-700'
                onClick={() => {
                  const target = confirmThreadDelete.threadId;
                  setConfirmThreadDelete({ open: false, threadId: null });
                  if (target) {
                    handleDeleteThread(target);
                  }
                }}
              >
                Supprimer
              </button>
            </div>
          </div>
        </div>
      )}

      {confirmProjectDelete && (
        <div className='fixed inset-0 z-50 flex items-center justify-center bg-black/40 px-4'>
          <div className='w-full max-w-sm rounded-2xl bg-white p-5 shadow-xl dark:bg-slate-900 dark:shadow-none'>
            <h4 className='text-base font-semibold text-gray-900 dark:text-slate-100'>
              Supprimer le projet
            </h4>
            <p className='mt-2 text-sm text-gray-600 dark:text-slate-300'>
              Ce projet sera supprimé et ses conversations détachées. Action
              irréversible.
            </p>
            <div className='mt-5 flex justify-end gap-2'>
              <button
                type='button'
                className='rounded-full border border-gray-200 px-4 py-2 text-xs font-semibold text-gray-600 hover:bg-gray-50 dark:border-slate-700 dark:text-slate-300 dark:hover:bg-slate-800'
                onClick={() => setConfirmProjectDelete(false)}
              >
                Annuler
              </button>
              <button
                type='button'
                className='rounded-full bg-red-600 px-4 py-2 text-xs font-semibold text-white hover:bg-red-700'
                onClick={() => {
                  setConfirmProjectDelete(false);
                  handleDelete();
                }}
              >
                Supprimer
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default Projects;
