// src/routes/login.jsx
import '../css/App.css';
import chatGPT from '../assets/chatGPT.gif';
import { useForm } from 'react-hook-form';
import axios from 'axios';
import React, { useState, useEffect } from 'react';
import { useUser } from '../UserContext';
import { API_BASE } from '../apiConfig';

const Login = () => {
  const {
    register,
    handleSubmit,
    watch,
    formState: { errors },
  } = useForm();
  const { userData, setUserData } = useUser();

  const onSubmit = data => {
    const { email, password } = data;
    axios
      .post(`${API_BASE}/login`, {
        email,
        password,
      })
      .then(response => {
        if (response.status === 200) {
          const { token, userId, username, email } = response.data;
          localStorage.setItem('token', token);
          localStorage.setItem(
            'user',
            JSON.stringify({ userId, username, email })
          );
          setUserData({
            id: userId,
            username: username,
            email: email,
          });
          window.location.href = '/';
        }
      })
      .catch(error => {
        if (error.response && error.response.status === 401) {
          if (
            error.response.data &&
            error.response.data.message === 'invalid email'
          ) {
            console.log('email invalide');
          }
        }
      });
  };

  return (
    <section className='py-16 xl:pb-56 bg-white overflow-hidden h-screen w-screen'>
      <div className='container px-4 mx-auto'>
        <div className='text-center max-w-md mx-auto'>
          <div className='inline-block w-32'>
            <img src={chatGPT} alt='Gif annimé robot' />
          </div>
          <h2 className='mb-4 text-6xl md:text-7xl text-center font-bold font-heading tracking-px-n leading-tight'>
            Welcome Back
          </h2>
          <p className='mb-12 font-medium text-lg text-gray-600 leading-normal'>
            Lorem ipsum dolor sit amet, to the con adipiscing. Volutpat tempor
            to the condim entum.
          </p>
          <form onSubmit={handleSubmit(onSubmit)}>
            <label className='block mb-5'>
              <input
                className='px-4 py-3.5 w-full text-gray-500 font-medium placeholder-gray-500 bg-white outline-none border border-gray-300 rounded-lg focus:ring focus:ring-teal-200'
                id='signInInput2-1'
                type='text'
                placeholder='Email address'
                {...register('email', { required: true })}
                autoComplete='email'
              />
            </label>
            <label className='relative block mb-5'>
              <div className='absolute right-4 top-1/2 transform -translate-y-1/2'>
                <a
                  className='text-sm text-teal-600 hover:text-teal-700 font-medium'
                  href='/reset-password-request'
                >
                  Forgot Password?
                </a>
              </div>
              <input
                className='px-4 pr-36 py-3.5 w-full text-gray-500 font-medium placeholder-gray-500 bg-white outline-none border border-gray-300 rounded-lg focus:ring focus:ring-teal-200'
                id='signInInput2-2'
                type='password'
                placeholder='Password'
                {...register('password', { required: true })}
                autoComplete='current-password'
              />
            </label>
            <button
              className='mb-8 py-4 px-9 w-full text-white font-semibold border border-teal-500 rounded-xl shadow-4xl focus:ring focus:ring-teal-200 bg-teal-400 hover:bg-teal-500 transition ease-in-out duration-200'
              type='submit'
            >
              Sign In
            </button>
          </form>
        </div>
      </div>
    </section>
  );
};

export default Login;

// frontend-svelte/src/routes/(auth)/login/+page.svelte
<script lang="ts">
  import { goto } from '$app/navigation';
  import { i18n } from '$lib/i18n/i18n.svelte';
  import { userStore } from '$lib/stores/user.svelte';
  import MatrixBackground from '$lib/components/common/MatrixBackground.svelte';

  let email = $state('');
  let password = $state('');
  let error = $state<string | null>(null);
  let loading = $state(false);

  const API_URL = import.meta.env.VITE_API_URL || '';

  async function handleSubmit(e: SubmitEvent) {
    e.preventDefault();
    error = null;

    if (!email) {
      error = i18n.t('emailRequired');
      return;
    }
    if (!password) {
      error = i18n.t('passwordRequired');
      return;
    }

    loading = true;
    try {
      const res = await fetch(`${API_URL}/login`, {
        method: 'POST',
        credentials: 'include',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email, password }),
      });

      const data: { user?: Record<string, unknown>; error?: string } & Record<string, unknown> = await res.json();

      if (!res.ok) {
        if (res.status === 403 && (data?.error as string)?.includes('verify')) {
          error = i18n.t('emailNotVerified');
        } else {
          error = i18n.t('invalidCredentials');
        }
        return;
      }

      const user = (data.user ?? data) as Record<string, unknown>;
      const normalized = {
        id: user.id as number,
        userId: user.id as number,
        username: user.username as string,
        email: user.email as string,
      };
      userStore.setUserData(normalized);
      localStorage.setItem('user', JSON.stringify(normalized));
      goto('/');
    } catch {
      error = i18n.t('invalidCredentials');
    } finally {
      loading = false;
    }
  }
</script>

<div class="relative min-h-screen flex items-center justify-center bg-background overflow-hidden">
  <MatrixBackground />

  <div class="relative z-10 w-full max-w-sm mx-4">
    <div class="bg-background/80 dark:bg-background/90 backdrop-blur-md border border-border rounded-2xl shadow-xl p-8">
      <div class="mb-8 text-center">
        <div class="inline-flex items-center justify-center w-12 h-12 rounded-xl bg-primary/10 mb-4">
          <span class="text-2xl">✦</span>
        </div>
        <h1 class="text-2xl font-bold text-foreground">{i18n.t('loginTitle')}</h1>
      </div>

      <form onsubmit={handleSubmit} class="space-y-4">
        <div>
          <label class="block text-sm font-medium text-foreground mb-1.5" for="email">
            {i18n.t('email')}
          </label>
          <input
            id="email"
            type="email"
            bind:value={email}
            placeholder={i18n.t('emailPlaceholder')}
            autocomplete="email"
            class="w-full rounded-lg border border-border bg-background px-3.5 py-2.5 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-primary/50 transition-shadow"
          />
        </div>

        <div>
          <label class="block text-sm font-medium text-foreground mb-1.5" for="password">
            {i18n.t('password')}
          </label>
          <input
            id="password"
            type="password"
            bind:value={password}
            placeholder={i18n.t('passwordPlaceholder')}
            autocomplete="current-password"
            class="w-full rounded-lg border border-border bg-background px-3.5 py-2.5 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-primary/50 transition-shadow"
          />
        </div>

        <div class="flex justify-end">
          <a
            href="/reset-password"
            class="text-xs text-muted-foreground hover:text-primary transition-colors"
          >
            {i18n.t('forgotPassword')}
          </a>
        </div>

        {#if error}
          <p class="text-sm text-destructive bg-destructive/10 rounded-lg px-3 py-2">{error}</p>
        {/if}

        <button
          type="submit"
          disabled={loading}
          class="w-full rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground transition-all hover:bg-primary/90 disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {loading ? i18n.t('connecting') : i18n.t('loginButton')}
        </button>
      </form>

      <p class="mt-6 text-center text-sm text-muted-foreground">
        {i18n.t('noAccount')}
        <a href="/register" class="font-medium text-primary hover:underline ml-1">
          {i18n.t('createAccount')}
        </a>
      </p>
    </div>
  </div>
</div>
