// frontend-svelte/src/lib/components/ui/Modal.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';

  interface Props {
    open: boolean;
    onClose: () => void;
    children: Snippet;
  }

  let { open, onClose, children }: Props = $props();
</script>

{#if open}
  <div
    class="fixed inset-0 z-50 flex items-center justify-center bg-black/30 px-4"
    onclick={onClose}
    role="dialog"
    aria-modal="true"
  >
    <div
      class="w-full max-w-md rounded-2xl bg-white p-6 shadow-xl dark:bg-card"
      onclick={(e) => e.stopPropagation()}
    >
      {@render children()}
    </div>
  </div>
{/if}

// frontend/src/components/common/Modal.tsx
import React from 'react';

const Modal = ({ isOpen, onClose, children }) => {
  if (!isOpen) return null;

  return (
    <div
      className='fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/30 backdrop-blur-sm'
      onClick={onClose}
    >
      <div
        className='relative w-full max-w-lg bg-white rounded-2xl shadow-2xl overflow-hidden max-h-[90vh] overflow-y-auto dark:bg-card dark:shadow-none'
        onClick={e => e.stopPropagation()}
      >
        <button
          onClick={onClose}
          className='absolute top-4 right-4 text-gray-400 hover:text-gray-600 z-10 transition-colors dark:text-muted-foreground dark:hover:text-foreground'
        >
          <svg
            className='w-6 h-6'
            fill='none'
            stroke='currentColor'
            viewBox='0 0 24 24'
          >
            <path
              strokeLinecap='round'
              strokeLinejoin='round'
              strokeWidth='2'
              d='M6 18L18 6M6 6l12 12'
            />
          </svg>
        </button>
        {children}
      </div>
    </div>
  );
};

export default Modal;
