// frontend-svelte/src/lib/components/chat/ChatSearchBar.svelte
<script lang="ts">
  import { ChevronUp, ChevronDown, X } from 'lucide-svelte';
  import type { ChatMessage } from '$lib/types';

  interface Props {
    messages: ChatMessage[];
    onScrollToIndex: (index: number) => void;
  }

  let { messages, onScrollToIndex }: Props = $props();

  let searchQuery = $state('');
  let rawMatchIndex = $state(0);
  let searchInputRef = $state<HTMLInputElement | null>(null);

  function normalizeContent(content: unknown): string {
    if (typeof content === 'string') return content;
    if (content === null || content === undefined) return '';
    try {
      return JSON.stringify(content);
    } catch {
      return String(content);
    }
  }

  let searchMatches = $derived.by(() => {
    if (!searchQuery.trim()) return [] as number[];
    const query = searchQuery.toLowerCase();
    return messages.reduce<number[]>((indices, message, index) => {
      const text = normalizeContent(message.content).toLowerCase();
      if (text.includes(query)) indices.push(index);
      return indices;
    }, []);
  });

  let searchMatchesCount = $derived(searchMatches.length);

  let activeMatchIndex = $derived(
    !searchQuery.trim() || searchMatchesCount === 0
      ? 0
      : Math.min(rawMatchIndex, searchMatchesCount - 1),
  );

  $effect(() => {
    if (searchMatchesCount > 0) {
      const msgIndex = searchMatches[activeMatchIndex];
      if (msgIndex !== undefined) {
        onScrollToIndex(msgIndex);
      }
    }
  });

  function handleNextMatch() {
    if (!searchMatchesCount) return;
    rawMatchIndex = (rawMatchIndex + 1) % searchMatchesCount;
  }

  function handlePrevMatch() {
    if (!searchMatchesCount) return;
    rawMatchIndex = rawMatchIndex - 1 < 0 ? searchMatchesCount - 1 : rawMatchIndex - 1;
  }

  function handleKeyDown(event: KeyboardEvent) {
    if (!searchQuery.trim()) return;
    if (event.key === 'Enter') {
      if (event.shiftKey) {
        handlePrevMatch();
      } else {
        handleNextMatch();
      }
    }
    if (event.key === 'Escape') {
      searchQuery = '';
    }
  }

  export function focus() {
    searchInputRef?.focus();
    searchInputRef?.select();
  }
</script>

<div
  class="flex items-center gap-2 rounded-full border border-gray-200 bg-white px-3 py-1.5 text-xs font-medium text-gray-600 shadow-sm dark:border-border dark:bg-card dark:text-foreground"
>
  <input
    bind:this={searchInputRef}
    type="search"
    bind:value={searchQuery}
    placeholder="Rechercher..."
    class="w-40 bg-transparent text-xs text-gray-600 outline-none placeholder:text-gray-400 dark:text-foreground dark:placeholder:text-muted-foreground"
    onkeydown={handleKeyDown}
  />

  {#if searchQuery}
    <button
      type="button"
      onclick={() => { searchQuery = ''; }}
      class="text-gray-400 transition hover:text-gray-600 dark:text-muted-foreground dark:hover:text-foreground"
      title="Effacer"
    >
      <X class="h-3 w-3" />
    </button>
  {/if}

  {#if searchQuery}
    <span
      class="rounded-full bg-teal-50 px-2 py-0.5 text-[10px] font-semibold text-teal-700 dark:bg-teal-500/10 dark:text-teal-200"
    >
      {searchMatchesCount} trouve{searchMatchesCount > 1 ? 's' : ''}
    </span>
  {/if}

  {#if searchQuery && searchMatchesCount > 0}
    <span class="text-[10px] text-gray-500 dark:text-muted-foreground">
      {activeMatchIndex + 1}/{searchMatchesCount}
    </span>
    <div class="flex items-center gap-1">
      <button
        type="button"
        onclick={handlePrevMatch}
        class="rounded-full border border-gray-200 bg-white p-0.5 text-gray-500 transition hover:border-gray-300 hover:text-gray-700 dark:border-border dark:bg-card dark:text-muted-foreground dark:hover:text-foreground"
        title="Precedent"
      >
        <ChevronUp class="h-3 w-3" />
      </button>
      <button
        type="button"
        onclick={handleNextMatch}
        class="rounded-full border border-gray-200 bg-white p-0.5 text-gray-500 transition hover:border-gray-300 hover:text-gray-700 dark:border-border dark:bg-card dark:text-muted-foreground dark:hover:text-foreground"
        title="Suivant"
      >
        <ChevronDown class="h-3 w-3" />
      </button>
    </div>
  {/if}
</div>

// frontend/src/features/chat/ChatSearchBar.tsx
import React, { useCallback, useEffect, useRef, useState, useMemo } from 'react';

function normalizeContent(content: unknown): string {
  if (typeof content === 'string') return content;
  if (content === null || content === undefined) return '';
  try {
    return JSON.stringify(content);
  } catch {
    return String(content);
  }
}

export function useChatSearch(messages: Array<{ content: string }>) {
  const [searchQuery, setSearchQuery] = useState('');
  const [rawMatchIndex, setRawMatchIndex] = useState(0);
  const searchInputRef = useRef<HTMLInputElement>(null);
  const mobileSearchInputRef = useRef<HTMLInputElement>(null);
  const [showMobileSearch, setShowMobileSearch] = useState(false);

  const searchMatches = useMemo<number[]>(() => {
    if (!searchQuery.trim()) return [];
    const query = searchQuery.toLowerCase();
    return messages.reduce<number[]>((indices, message, index) => {
      const text = normalizeContent(message.content).toLowerCase();
      if (text.includes(query)) indices.push(index);
      return indices;
    }, []);
  }, [messages, searchQuery]);

  const searchMatchesCount = searchMatches.length;

  const activeMatchIndex = useMemo(() => {
    if (!searchQuery.trim() || searchMatchesCount === 0) return 0;
    return Math.min(rawMatchIndex, searchMatchesCount - 1);
  }, [rawMatchIndex, searchMatchesCount, searchQuery]);

  const activeMessageIndex =
    searchMatchesCount > 0 && activeMatchIndex >= 0
      ? searchMatches[activeMatchIndex]
      : null;

  const handleNextMatch = useCallback(() => {
    if (!searchMatchesCount) return;
    setRawMatchIndex(prev => (prev + 1) % searchMatchesCount);
  }, [searchMatchesCount]);

  const handlePrevMatch = useCallback(() => {
    if (!searchMatchesCount) return;
    setRawMatchIndex(prev =>
      prev - 1 < 0 ? searchMatchesCount - 1 : prev - 1,
    );
  }, [searchMatchesCount]);

  useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'f') {
        if (searchInputRef.current) {
          event.preventDefault();
          searchInputRef.current.focus();
          searchInputRef.current.select();
        }
        return;
      }
      if (!searchQuery || !searchQuery.trim()) return;
      if (event.key !== 'Enter') return;
      if (event.shiftKey) {
        handlePrevMatch();
      } else {
        handleNextMatch();
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [handleNextMatch, handlePrevMatch, searchQuery]);

  useEffect(() => {
    if (!showMobileSearch) return;
    mobileSearchInputRef.current?.focus();
  }, [showMobileSearch]);

  return {
    searchQuery,
    setSearchQuery,
    activeMatchIndex,
    searchMatchesCount,
    activeMessageIndex,
    handleNextMatch,
    handlePrevMatch,
    searchInputRef,
    mobileSearchInputRef,
    showMobileSearch,
    setShowMobileSearch,
  };
}

type SearchControlsProps = {
  inputRef: React.RefObject<HTMLInputElement | null>;
  sizeClass: string;
  searchQuery: string;
  setSearchQuery: (q: string) => void;
  searchMatchesCount: number;
  activeMatchIndex: number;
  handlePrevMatch: () => void;
  handleNextMatch: () => void;
};

export function SearchControls({
  inputRef,
  sizeClass,
  searchQuery,
  setSearchQuery,
  searchMatchesCount,
  activeMatchIndex,
  handlePrevMatch,
  handleNextMatch,
}: SearchControlsProps) {
  return (
    <div
      className={`flex items-center gap-2 rounded-full border border-gray-200 bg-white px-3 py-1.5 text-xs font-medium text-gray-600 shadow-sm dark:border-border dark:bg-card dark:text-foreground ${sizeClass}`}
    >
      <input
        type='search'
        ref={inputRef}
        value={searchQuery}
        onChange={event => setSearchQuery(event.target.value)}
        placeholder='Rechercher\u2026'
        className='w-40 bg-transparent text-xs text-gray-600 placeholder:text-gray-400 outline-none dark:text-foreground dark:placeholder:text-muted-foreground'
      />
      {searchQuery && (
        <button
          type='button'
          className='text-gray-400 transition hover:text-gray-600 dark:text-muted-foreground dark:hover:text-foreground'
          onClick={() => setSearchQuery('')}
        >
          Effacer
        </button>
      )}
      {searchQuery && (
        <span className='rounded-full bg-teal-50 px-2 py-0.5 text-[10px] font-semibold text-teal-700 dark:bg-teal-500/10 dark:text-teal-200'>
          {searchMatchesCount} trouv\u00e9{searchMatchesCount > 1 ? 's' : ''}
        </span>
      )}
      {searchQuery && searchMatchesCount > 0 && (
        <span className='flex items-center gap-1 text-[10px] text-gray-500 dark:text-muted-foreground'>
          {activeMatchIndex + 1}/{searchMatchesCount}
        </span>
      )}
      {searchQuery && searchMatchesCount > 0 && (
        <div className='flex items-center gap-1'>
          <button
            type='button'
            onClick={handlePrevMatch}
            className='rounded-full border border-gray-200 bg-white px-2 py-0.5 text-[10px] font-semibold text-gray-500 transition hover:border-gray-300 hover:text-gray-700 dark:border-border dark:bg-card dark:text-muted-foreground dark:hover:text-foreground'
          >
            Pr\u00e9c\u00e9dent
          </button>
          <button
            type='button'
            onClick={handleNextMatch}
            className='rounded-full border border-gray-200 bg-white px-2 py-0.5 text-[10px] font-semibold text-gray-500 transition hover:border-gray-300 hover:text-gray-700 dark:border-border dark:bg-card dark:text-muted-foreground dark:hover:text-foreground'
          >
            Suivant
          </button>
        </div>
      )}
    </div>
  );
}

type MobileSearchPanelProps = {
  showMobileSearch: boolean;
  setShowMobileSearch: (v: boolean) => void;
  mobileSearchInputRef: React.RefObject<HTMLInputElement | null>;
  searchQuery: string;
  setSearchQuery: (q: string) => void;
  searchMatchesCount: number;
  activeMatchIndex: number;
  handlePrevMatch: () => void;
  handleNextMatch: () => void;
};

export function MobileSearchPanel({
  showMobileSearch,
  setShowMobileSearch,
  mobileSearchInputRef,
  searchQuery,
  setSearchQuery,
  searchMatchesCount,
  activeMatchIndex,
  handlePrevMatch,
  handleNextMatch,
}: MobileSearchPanelProps) {
  return (
    <div
      className={`mx-auto w-full max-w-4xl px-4 pt-3 sm:hidden transition-all duration-200 ${
        showMobileSearch
          ? 'max-h-[260px] opacity-100'
          : 'pointer-events-none max-h-0 opacity-0'
      }`}
    >
      <div className='overflow-hidden rounded-2xl border border-gray-200 bg-white/90 p-3 shadow-sm dark:border-border dark:bg-card/80'>
        <div className='mb-3 flex items-center justify-between'>
          <div className='text-xs font-semibold text-gray-600 dark:text-muted-foreground'>
            Recherche
          </div>
          <button
            type='button'
            onClick={() => setShowMobileSearch(false)}
            className='rounded-full border border-gray-200 bg-white px-2 py-0.5 text-[10px] font-semibold text-gray-500 transition hover:border-gray-300 hover:text-gray-700 dark:border-border dark:bg-card dark:text-muted-foreground dark:hover:text-foreground'
          >
            Fermer
          </button>
        </div>
        <SearchControls
          inputRef={mobileSearchInputRef}
          sizeClass='w-full'
          searchQuery={searchQuery}
          setSearchQuery={setSearchQuery}
          searchMatchesCount={searchMatchesCount}
          activeMatchIndex={activeMatchIndex}
          handlePrevMatch={handlePrevMatch}
          handleNextMatch={handleNextMatch}
        />
        <div className='mt-3 rounded-xl border border-gray-100 bg-gray-50 px-3 py-2 text-[11px] text-gray-500 dark:border-border dark:bg-muted dark:text-muted-foreground'>
          {searchQuery
            ? `${searchMatchesCount} r\u00e9sultat${
                searchMatchesCount > 1 ? 's' : ''
              } \u00b7 ${activeMatchIndex + 1}/${
                searchMatchesCount || 0
              } affich\u00e9`
            : 'Entrez un mot-cl\u00e9 pour rechercher dans la conversation.'}
        </div>
      </div>
    </div>
  );
}
